const assert = require('node:assert/strict')
const qml = require('node:fs').readFileSync('Panel.qml', 'utf8')

for (const name of ['Model.rows(', 'KeyboardPanel {', 'PanelKeyCatcher {', 'root.badgeGlyph', 'source.pendingMode', 'source.failed', 'Quickshell.screens[0]'])
  assert.ok(qml.includes(name), `missing panel behavior: ${name}`)
assert.ok(/primary:\s*!!root\.QsWindow\.window && Quickshell\.screens\.length > 0 &&\s*root\.QsWindow\.window\.screen\.name === Quickshell\.screens\[0\]\.name/.test(qml), 'only the first bar owns the cache')
assert.ok(qml.includes('Model.shellQuote(Model.localFilePath(Qt.resolvedUrl("scripts/enable")))'), 'enable passes a quoted local path to the launcher')
assert.ok(/\["busctl", "--user", "--auto-start=no", "call", "org\.fcitx\.Fcitx5", "\/controller",\s*"org\.fcitx\.Fcitx\.Controller1", "Toggle"\]/.test(qml), 'right click uses a non-activating D-Bus call')
assert.ok(!qml.includes('fcitx5-remote') && !qml.includes('toggleCheck'), 'no race-prone remote toggle')
assert.ok(/function menuOpen\(\): bool \{ return root\.opened \}/.test(qml), 'E2E key guard must read the plugin’s actual open state')
assert.ok(qml.includes('if (source.status !== "ready") source.checkController()'), 'opening a down menu rechecks the controller')
assert.ok(/else if \(source\.hasFocusedWindow\) source\.refresh\(\)/.test(qml), 'opening a ready menu with focus refreshes its group once')
assert.ok(qml.includes('s.badgeGlyph = root.badgeGlyph') && qml.includes('s.badgeTitle = root.badgeTitle') && qml.includes('s.rows = root.rows') && qml.includes('s.selectedIndex = root.selectedIndex') && qml.includes('s.cursorActive = root.cursorActive'), 'IPC exposes rendered badge, menu rows and selection')
assert.ok(!qml.includes('function verifyProbe()'), 'no test-only process launcher in production IPC')
assert.ok(qml.includes('source.checkController()'), 'controller recheck remains on menu open')
assert.ok(qml.includes('function mouseTarget(index: int): string') && qml.includes('var row = inputRows.itemAt(index)') && qml.includes('row.mapToItem(null,'), 'mouse test locates actual rendered row geometry')
const source = require('node:fs').readFileSync('FcitxSource.qml', 'utf8')
assert.ok(source.includes('function checkController()'), 'source owns the controller recheck')
assert.ok(source.includes('processStarts: processStarts') && source.includes('focusEvents: focusVersion'), 'IPC exposes monotonic spawn and focus-event counters')
assert.ok(/if \(!root\.pendingIm && !root\.hasValidSnapshot\) root\.refresh\(\)/.test(source), 'focus loss retries one provisional snapshot through the existing Process')
assert.ok(/if \(!trayItem && bestEffort\)/.test(source), 'tray loss re-arms only provisional state')
assert.ok(source.includes('!hasFocusedWindow && (hasValidSnapshot || !trayItem)'), 'no-focus snapshot cannot start while SNI is absent')
assert.ok(source.includes('methods.find(function(e) { return e.icon === s.icon'), 'when fcitx5 checks no row after restart, the published IM icon still seeds a top-level row')
assert.equal((source.match(/onRunningChanged: if \(running\) root\.processStarts \+= 1/g) || []).length, 3, 'all source Processes count starts')
assert.ok(qml.includes('onRunningChanged: if (running) source.processStarts += 1'), 'panel config check counts starts')
assert.ok(/onActivateRequested:\s*root\.activate\(root\.selectedIndex\)/.test(qml), 'Enter/Space activates the selected row without mouse or arrow')
const verify = require('node:fs').readFileSync('verify.sh', 'utf8')
assert.ok(verify.includes('REFUSE: close all client windows before testing'), 'cannot restart fcitx5 under an existing client input context')
assert.ok(verify.includes('in-progress') && verify.includes('--recover') && verify.includes('--status'), 'durable recovery interface')
assert.ok(verify.includes('BACKUP="$STATE_DIR/backups"') && verify.includes('TYPED="$STATE_DIR/typed-output"') && !verify.includes('jq -r .backup "$MANIFEST"'), 'recovery paths must be fixed, never loaded from manifest')
assert.ok(verify.includes('PREVIEW ONLY: nothing changed.') && verify.includes('--yes-restart-fcitx5'), 'recovery previews before explicit overwrite/restart consent')
assert.ok(verify.includes('SKIP: idle-multi-monitor') && verify.includes('invalid or empty monitor array'), 'per-instance counter cannot claim multi-monitor or malformed-monitor coverage')
assert.ok(!verify.includes('C verifyProbe'), 'positive control uses a normal lifecycle path')
assert.ok(verify.includes('"$STATE_DIR/scratch.XXXXXX"') && verify.includes('"$STATE_DIR/restore.json.tmp.XXXXXX"'), 'scratch and manifest staging stay private and recoverable')
assert.ok(verify.includes('sweep_stale') && verify.includes('pre_marker_cleanup'), 'safe runs sweep orphan scratch and pre-marker exits clean up')
assert.ok(verify.includes('sleep 0.25\n  done\n  [[ -r /proc/$pid/cmdline'), 'newly started fcitx5 is boundedly awaited before launch-command verification')
assert.ok(verify.indexOf('rm -f -- "$MARKER"') < verify.indexOf('rm -r -- "$BACKUP"', verify.indexOf('rm -f -- "$MARKER"')), 'marker is removed before backup garbage collection')
console.log('panel wiring OK')
