const assert = require('node:assert/strict')
const qml = require('node:fs').readFileSync('Panel.qml', 'utf8')

for (const name of ['Model.rows(', 'KeyboardPanel {', 'PanelKeyCatcher {', 'root.badgeGlyph', 'source.pendingMode', 'source.failed', 'Quickshell.screens[0]'])
  assert.ok(qml.includes(name), `missing panel behavior: ${name}`)
assert.ok(/primary:\s*!!root\.QsWindow\.window && Quickshell\.screens\.length > 0 &&\s*root\.QsWindow\.window\.screen\.name === Quickshell\.screens\[0\]\.name/.test(qml), 'only the first bar owns the cache')
assert.ok(qml.includes('Model.shellQuote(Model.localFilePath(Qt.resolvedUrl("scripts/enable")))'), 'enable passes a quoted local path to the launcher')
assert.ok(/\["busctl", "--user", "--auto-start=no", "call", "org\.fcitx\.Fcitx5", "\/controller",\s*"org\.fcitx\.Fcitx\.Controller1", "Toggle"\]/.test(qml), 'right click uses a non-activating D-Bus call')
assert.ok(!qml.includes('fcitx5-remote') && !qml.includes('toggleCheck'), 'no race-prone remote toggle')
assert.ok(/function menuOpen\(\): bool \{ return root\.opened \}/.test(qml), 'E2E key guard must read the plugin’s actual open state')
assert.ok(qml.includes('if (source.status !== "ready") source.checkController()'), 'opening a down menu rechecks the controller')
assert.ok(/else if \(source\.hasFocusedWindow\) source\.refresh\(\)/.test(qml), 'opening a ready menu with focus refreshes its group once')
assert.ok(qml.includes('s.badgeGlyph = root.badgeGlyph') && qml.includes('s.badgeTitle = root.badgeTitle') && qml.includes('s.rows = root.rows') && qml.includes('s.selectedIndex = root.selectedIndex') && qml.includes('s.cursorActive = root.cursorActive'), 'IPC exposes rendered badge, menu rows and selection')
assert.ok(!qml.includes('function verifyProbe()'), 'no test-only process launcher in production IPC')
assert.ok(qml.includes('source.checkController()'), 'controller recheck remains on menu open')
assert.ok(qml.includes('function mouseTarget(index: int): string') && qml.includes('var row = inputRows.itemAt(index)') && qml.includes('row.mapToItem(null,'), 'mouse test locates actual rendered row geometry')
const source = require('node:fs').readFileSync('FcitxSource.qml', 'utf8')
assert.ok(source.includes('function checkController()'), 'source owns the controller recheck')
assert.ok(source.includes('processStarts: processStarts') && source.includes('focusEvents: focusVersion'), 'IPC exposes monotonic spawn and focus-event counters')
assert.ok(/if \(!root\.pendingIm && !root\.hasValidSnapshot\) root\.refresh\(\)/.test(source), 'focus loss retries one provisional snapshot through the existing Process')
assert.ok(/if \(!trayItem && bestEffort\)/.test(source), 'tray loss re-arms only provisional state')
assert.ok(/if \(trayItem && !hasFocusedWindow\) hasValidSnapshot = false/.test(source), 'a new tray item (fcitx5 restart) drops the stale snapshot so an empty desk reads the new input method list')
assert.ok(source.includes('!hasFocusedWindow && (hasValidSnapshot || !trayItem)'), 'no-focus snapshot cannot start while SNI is absent')
assert.ok(source.includes('methods.find(function(e) { return e.icon === s.icon'), 'when fcitx5 checks no row after restart, the published IM icon still seeds a top-level row')
assert.equal((source.match(/onRunningChanged: if \(running\) root\.processStarts \+= 1/g) || []).length, 3, 'all source Processes count starts')
assert.ok(qml.includes('onRunningChanged: if (running) source.processStarts += 1'), 'panel config check counts starts')
assert.ok(qml.includes('property string themeState: ""'), 'theme state starts unknown')
const panelProcesses = qml.match(/  Process \{[\s\S]*?\n  \}/g) || []
assert.equal(panelProcesses.length, 2, 'config check and theme status are the only panel Processes')
for (const process of panelProcesses)
  assert.ok(process.includes('onRunningChanged: if (running) source.processStarts += 1'), 'every panel Process counts starts')
const themeProcess = panelProcesses.find(process => process.includes('id: themeProc')) || ''
assert.ok(themeProcess.includes('command: [Model.localFilePath(Qt.resolvedUrl("scripts/theme")), "status"]'), 'theme status uses the local script')
assert.ok(/stdout: StdioCollector \{\s*waitForEnd: true\s*onStreamFinished: root\.themeState = text\.trim\(\)/.test(themeProcess), 'theme status is collected after completion')
const menuOpen = qml.match(/onOpenedChanged: if \(opened\) \{([\s\S]*?)\n  \}/)
assert.ok(menuOpen && menuOpen[1].includes('themeProc.running = true'), 'theme status starts when the menu opens')
assert.equal((qml.match(/themeProc\.running\s*=/g) || []).length, 1, 'no other path starts theme status')
assert.ok(!qml.includes('Timer {') && !/running:\s*true/.test(themeProcess), 'no timer or idle theme status launch')
assert.ok(qml.includes('Model.shellQuote(Model.localFilePath(Qt.resolvedUrl("scripts/theme"))) + " enable"'), 'match theme passes the quoted path and enable to the presentation launcher')
assert.ok(/a\.id === "matchTheme"\) launchOnce\("scripts\/theme enable", \["omarchy-launch-floating-terminal-with-presentation",/.test(qml), 'match theme uses the same launcher as tray enable')
assert.ok(qml.includes('Model.shellQuote(Model.localFilePath(Qt.resolvedUrl("scripts/add-engine")))'), 'install input methods passes a quoted local path to the launcher')
assert.ok(/a\.id === "installIm"\) launchOnce\("scripts\/add-engine", \["omarchy-launch-floating-terminal-with-presentation",/.test(qml), 'install input methods uses the same counted launcher as tray enable')
assert.equal((qml.match(/Qt\.resolvedUrl\("scripts\/add-engine"\)/g) || []).length, 1, 'add-engine is referenced only by its action launcher')
assert.ok(!qml.includes('str.addIm'), 'the configtool-only single-input-method action is gone')
const extrasBody = qml.match(/readonly property var extras: \{([\s\S]*?)\n  \}/)[1]
const extrasFor = new Function('source', 'str', 'hasConfigTool', 'themeState', extrasBody)
for (const state of ['', 'enabled', 'free', 'claimed']) {
  const extras = extrasFor({ status: 'ready', singleInputMethod: false, failed: false }, {}, true, state)
  assert.equal(extras.filter(row => row.id === 'matchTheme').length, state === 'free' || state === 'claimed' ? 1 : 0, `theme footer visibility: ${state}`)
  if (state === 'free' || state === 'claimed') {
    const index = extras.findIndex(row => row.id === 'matchTheme')
    assert.equal(extras[index].kind, 'action')
    assert.equal(extras[index - 1].id, 'installIm', 'match theme follows the install action after emoji')
  }
}
const strings = require('../Model.js').strings('en')
for (const hasConfigTool of [false, true]) {
  for (const singleInputMethod of [false, true]) {
    const extras = extrasFor({ status: 'ready', singleInputMethod, failed: false }, strings, hasConfigTool, 'free')
    const install = extras.filter(row => row.id === 'installIm')
    assert.deepEqual(install, [{ kind: 'action', id: 'installIm', title: strings.installIm }], 'exactly one install action, independent of configtool')
    const separator = extras.findIndex(row => row.kind === 'separator')
    const index = extras.findIndex(row => row.id === 'installIm')
    if (singleInputMethod) {
      assert.equal(index, 1, 'the single-input-method notice is followed by its install action')
      assert.deepEqual(extras[0], { kind: 'notice', title: strings.onlyOne })
      assert.ok(index < separator, 'single-input-method install action is not repeated in the footer')
    } else {
      assert.ok(index > separator, 'normal install action belongs to the footer')
      assert.equal(extras[index - 1].id, 'emoji', 'normal install action immediately follows emoji')
    }
    assert.deepEqual(extras.filter(row => row.id === 'settings'), hasConfigTool ? [{ kind: 'action', id: 'settings', title: strings.settings }] : [], 'settings retains its own configtool gate and title')
    assert.equal(extras.filter(row => row.kind === 'action').filter(row => row.id === 'installIm').length, 1, 'actionRows contains install once')
  }
}
for (const hasConfigTool of [false, true]) {
  for (const status of ['down', 'noSni']) {
    const extras = extrasFor({ status, singleInputMethod: false, failed: false }, strings, hasConfigTool, 'free')
    assert.deepEqual(extras.filter(row => row.id === 'installIm'), status === 'down' ? [] : [{ kind: 'action', id: 'installIm', title: strings.installIm }], `install visibility when ${status}`)
    assert.equal(extras[1].id, status === 'down' ? 'start' : 'enable', 'unavailable-source notice retains its way forward')
    if (status === 'noSni') {
      const index = extras.findIndex(row => row.id === 'installIm')
      assert.equal(extras[index - 1].id, 'emoji', 'noSni keeps install immediately after emoji')
    }
    assert.deepEqual(extras.filter(row => row.id === 'settings'), hasConfigTool ? [{ kind: 'action', id: 'settings', title: strings.settings }] : [], 'settings gate is independent of source status')
  }
}
assert.ok(!/actionRows\.indexOf\(/.test(qml) && qml.includes('root.actionOrdinal(index)'), 'action row index comes from position, not object identity')
for (const id of ["emoji", "settings", "enable", "installIm", "matchTheme"]) {
  assert.ok(new RegExp('a\\.id === "' + id + '"\\) launchOnce\\(').test(qml), id + ' action starts through the single-instance guard')
}
assert.ok(!/a\.id === "[a-zA-Z]+"\) launch\(\[/.test(qml.replace(/a\.id === "start"\) launch\(/, "")), 'no action launches without the guard (except starting fcitx5)')
const enable = require('node:fs').readFileSync('scripts/enable', 'utf8')
const disable = require('node:fs').readFileSync('scripts/disable', 'utf8')
assert.ok(enable.trimEnd().endsWith('"$(dirname "$0")/theme" enable --auto || true'), 'theme is best-effort after successful tray enable')
assert.ok(disable.indexOf('"$(dirname "$0")/theme" disable || theme_pending=1') > disable.indexOf('set -euo pipefail') && disable.indexOf('"$(dirname "$0")/theme" disable || theme_pending=1') < disable.indexOf('DROPIN='), 'theme disable records a non-fatal failure before tray teardown')
assert.ok(/onActivateRequested:\s*root\.activate\(root\.selectedIndex\)/.test(qml), 'Enter/Space activates the selected row without mouse or arrow')
const verify = require('node:fs').readFileSync('verify.sh', 'utf8')
assert.ok(verify.includes('REFUSE: close all client windows before testing'), 'cannot restart fcitx5 under an existing client input context')
assert.ok(verify.includes('in-progress') && verify.includes('--recover') && verify.includes('--status'), 'durable recovery interface')
assert.ok(verify.includes('BACKUP="$STATE_DIR/backups"') && verify.includes('TYPED="$STATE_DIR/typed-output"') && !verify.includes('jq -r .backup "$MANIFEST"'), 'recovery paths must be fixed, never loaded from manifest')
assert.ok(verify.includes('PREVIEW ONLY: nothing changed.') && verify.includes('--yes-restart-fcitx5'), 'recovery previews before explicit overwrite/restart consent')
assert.ok(verify.includes('SKIP: idle-multi-monitor') && verify.includes('invalid or empty monitor array'), 'per-instance counter cannot claim multi-monitor or malformed-monitor coverage')
assert.ok(!verify.includes('C verifyProbe'), 'positive control uses a normal lifecycle path')
assert.ok(verify.includes('"$STATE_DIR/scratch.XXXXXX"') && verify.includes('"$STATE_DIR/restore.json.tmp.XXXXXX"'), 'scratch and manifest staging stay private and recoverable')
assert.ok(verify.includes('sweep_stale') && verify.includes('pre_marker_cleanup'), 'safe runs sweep orphan scratch and pre-marker exits clean up')
assert.ok(verify.includes('sleep 0.25\n  done\n  [[ -r /proc/$pid/cmdline'), 'newly started fcitx5 is boundedly awaited before launch-command verification')
assert.ok(verify.indexOf('rm -f -- "$MARKER"') < verify.indexOf('rm -r -- "$BACKUP"', verify.indexOf('rm -f -- "$MARKER"')), 'marker is removed before backup garbage collection')
assert.ok(verify.includes('candidateHashes') && verify.includes('original_classicui'), 'recovery includes candidate theme files and classicui values')
assert.ok(verify.includes('candidate_path()') && verify.includes('restore_candidate()'), 'candidate restore targets are derived by code')
assert.ok(verify.includes("step 'candidate theme ownership and idempotence'"), 'candidate theme assertions are runnable')
assert.ok(verify.indexOf("step 'candidate theme ownership and idempotence'") < verify.indexOf("step 'isolate Input Menu"), 'candidate assertions precede shell isolation')
assert.ok(verify.includes('current/theme/colors.toml') && verify.includes('theme-tokyo-night'), 'independent palette and mid-theme interruption coverage')
assert.ok(verify.includes('close owned window before noSni restart') && verify.includes('fresh owned context after noSni restart'), 'noSni restarts preserve the zero-client guard and get a fresh context')
assert.ok(verify.includes('client windows remained open; fcitx5 was not restarted'), 'restoration refuses unsafe service restarts')
assert.ok(verify.includes("step 'guided install with installed engines'"), 'installed-engine install flow is verified on the device')
assert.ok(verify.includes('injected_failure guided-install'), 'guided install has a durable interruption checkpoint')
assert.ok(verify.includes('"$SCRATCH/pkg-guard/omarchy-pkg-add"') && verify.includes('INPUT_MENU_PKG_LOG='), 'guided install refuses any real package installation through a scoped failing stub')
assert.ok(verify.includes("step 'Hiragana selected by menu keyboard from active Katakana, then typed into a new window'"), 'keyboard selection tests a visible mode from active hidden Katakana')
assert.ok(verify.includes("step 'default Hiragana menu has only ABC, Zhuyin and Hiragana'"), 'default hidden modes are checked on the device')
assert.ok(verify.includes("step 'empty desk drops removed Mozc after fcitx5 restart'"), 'empty-desk restart refreshes the input-method list on the device')
assert.ok(!verify.includes(" SetInputMethodGroup '"), 'group writes use the existing SetInputMethodGroupInfo D-Bus method')
assert.equal((verify.match(/menu_select_row "\$target_index"/g) || []).length, 2, 'both keyboard checks target an input row instead of assuming the old row count')
console.log('panel wiring OK')
